HELLO_LIST = [
    "hello",
    "hi",
    "hey",
    "yo",
    "sup",
    "howdy",
    "what's up",
    "hiya",
    "g'day",
    "holla",
    "привіт",
    "вітаю",
    "здоров!",
    "доброго дня",
    "йо",
    "чувак, привіт",
    "салют",
    "хай",
    "здарова",
    "шалом",
    "привет",
    "здорово",
    "здравствуйте",
    "добрый день",
    "ку",
    "дарова",
    "хай",
    "алло",
    "прив",
    "шалом",
    "yo yo",
    "hey there",
    "hola",
    "wassup",
    "wazzup",
    "bonjour",
    "ciao",
    "namaste",
    "aloha",
    "hallo",
    "hey dude",
    "hey bro",
    "whaddup",
    "ayyy",
    "sup bro",
    "yo man",
    "greetings",
    "good day",
    "what's good",
    "пр",
    "прив",
    "hey mate",
    "مرحبًا",
]

INFO_LIST = [
    "инфо",
    "info",
    "information",
    "data",
    "details",
    "facts",
    "news",
    "insight",
    "intel",
    "knowledge",
    "scoop",
    "інформація",
    "інфа",
    "дані",
    "факти",
    "відомості",
    "новини",
    "інсайд",
    "знання",
    "свідчення",
    "контент",
    "информация",
    "инфа",
    "данные",
    "факты",
    "сведения",
    "новости",
    "инсайд",
    "знания",
    "контент",
    "справка",
    "deets",
    "411",
    "inside scoop",
    "lowdown",
    "buzz",
    "heads-up",
    "brief",
    "leak",
    "gossip",
    "update",
    "report",
    "summary",
    "announcement",
    "intel drop",
    "sneak peek",
    "overview",
    "newsflash",
    "hot tip",
    "word",
    "memo",
    "415 я база ответе",
]

BOT_GAME_LIST = [
    "play",
    "играть",
    "contest",
    "match",
    "tournament",
    "competition",
    "play",
    "event",
    "sport",
    "challenge",
    "battle",
    "competition",
    "змагання",
    "турнір",
    "конкурс",
    "подія",
    "спортивне змагання",
    "вистава",
    "битва",
    "соревнование",
    "турнир",
    "конкурс",
    "мероприятие",
    "спортивное соревнование",
    "выступление",
    "битва",
]

MISUNDERSTANDING_STICKERS = [
    "CAACAgIAAxkBAAEOHKZn2by_ODRXDsyJdcYvEEuvs_ZbVAACKEoAAuNUcEoOR1AN9xD3_zYE",
    "CAACAgIAAxkBAAEOHKhn2b2MG0IpXmHxJnXn14mNZYK1qQACVRwAAncPWEvP6sxUrYQ-MTYE",
    "CAACAgIAAxkBAAEOHKpn2b2Vvsc8uj0RyU25J1Igz8WCHwACTBkAAl11-Ujbhgg6l6SFnjYE",
    "CAACAgIAAxkBAAEOIGln3GEMlWYOnQXntyL5i5q7CC9LlgACpkIAAhGaYEiJjxDLkrWOETYE",
    "CAACAgIAAxkBAAEOIGtn3GER98RPksgH7sE9cw8wc4B6jgACGVUAAmIucUosnuoCIZR6ZDYE",
]

GAME_CHOICES = [
    "да",
    "нет",
    "естествено",
    "естествено нет",
    "да но не сегедня",
]
